# .github/workflows/main.yml

name: CI - Testes de API (Pytest/Allure)

# 1. Quando o Workflow deve rodar?
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 2. Define o Job principal
jobs:
  test_api:
    runs-on: ubuntu-latest # Usa a máquina virtual Linux do GitHub

    # Define a versão do Python
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    # 3. Instala as dependências
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Instala os pacotes necessários para API e relatórios
        pip install pytest requests allure-pytest

    # 4. Executa os Testes de API
    - name: Run Pytest and Generate Allure Results
      # O Pytest rodará os 6 testes e gerará os arquivos brutos do relatório
      run: |
        pytest tests/api --alluredir=reports/allure-results

    # 5. Publica o Relatório Allure (Opcional, mas útil)
    # Esta etapa torna os resultados visíveis na página "Actions" do GitHub
    - name: Publish Allure Report Results
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-results
        path: reports/allure-results
        # Não precisa da badge "Allure Report" no README, mas garante que os resultados brutos fiquem salvos.
